# Generated by Django 4.0.6 on 2022-08-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Health Care', 'Health Care'), ('Inspiration', 'Inspiration'), ('Travel news', 'Travel news'), ('Product', 'Product'), ('Resaurant food', 'Resaurant food'), ('Pharmacy', 'Pharmacy'), ('Computer science', 'Computer science'), ('Modern technology', 'Modern technology'), ('Finance', 'Finance'), ('Others', 'Others')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
