# Generated by Django 4.0.6 on 2022-07-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_category_job_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Vacancy',
            new_name='vacancy',
        ),
    ]
