# Generated by Django 4.0.6 on 2022-07-28 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_apply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='cv',
            new_name='uplode_cv',
        ),
    ]
